### ISSUE TITLE
Sign Up form

### ISSUE THREAD

**Issue by Abhishek-Sai** [aravindvnair99/Smart-India-Hackathon-2019#3]
- Mobile Number
- Check if user used OTP or email to login, and pre-fill that particular field.
- First name, Last name in firebase authentication

**Comment by Abhishek-Sai** [comment]
- Auto Complete
- Password UI

**Comment by aravindvnair99** [comment]
Need to fix file upload.

**Comment by aravindvnair99** [comment]
Fixed in 9cb860ed5fa0e863776ba7b6f55afe95b6b28a9b
